import test from 'node:test'
import assert from 'node:assert/strict'
import { createPhase2Server } from '../dist/apps/web/src/server.js'

function opened(ws){return new Promise((resolve,reject)=>{ws.addEventListener('open',resolve,{once:true});ws.addEventListener('error',reject,{once:true})})}
function message(ws,predicate,timeout=3000){return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{ws.removeEventListener('message',listener);reject(new Error('message timeout'))},timeout);function listener(event){const value=JSON.parse(String(event.data));if(predicate(value)){clearTimeout(timer);ws.removeEventListener('message',listener);resolve(value)}}ws.addEventListener('message',listener)})}
function close(ws){try{ws.close()}catch{}}

test('two WebSocket clients synchronize updates, presence, and reconnect diffs',async()=>{const app=createPhase2Server({port:0,databasePath:':memory:',syncDatabasePath:':memory:'});const started=await app.start();const url=started.url.replace('http','ws')+'/sync';const a=new WebSocket(url),b=new WebSocket(url);try{await Promise.all([opened(a),opened(b)]);a.send(JSON.stringify({type:'hello',clientId:'a',stateVector:{},presence:{clientId:'a',actorType:'agent',actorId:'a',label:'A',updatedAt:''}}));b.send(JSON.stringify({type:'hello',clientId:'b',stateVector:{},presence:{clientId:'b',actorType:'agent',actorId:'b',label:'B',updatedAt:''}}));await Promise.all([message(a,m=>m.type==='hello_ack'),message(b,m=>m.type==='hello_ack')]);const seed=app.room.nextUpdate('a',app.createSeedTransaction());const seen=message(b,m=>m.type==='update'&&m.update.updateId===seed.updateId);a.send(JSON.stringify({type:'update',update:seed}));await seen;assert.equal(app.store.listObjects(app.rootCanvas.id).length,8);const oldVector=app.room.stateVector();close(b);await new Promise(r=>setTimeout(r,80));const repair=app.room.nextUpdate('a',app.createRepairTransaction());const repaired=message(a,m=>m.type==='update'&&m.update.updateId===repair.updateId);a.send(JSON.stringify({type:'update',update:repair}));await repaired;const b2=new WebSocket(url);await opened(b2);b2.send(JSON.stringify({type:'hello',clientId:'b2',stateVector:oldVector,presence:{clientId:'b2',actorType:'agent',actorId:'b2',label:'B2',updatedAt:''}}));const ack=await message(b2,m=>m.type==='hello_ack');assert.equal(ack.missingUpdates.length,1);assert.equal(app.store.getObject('title').transform.y,55);assert.ok(ack.presence.some(p=>p.clientId==='b2'));close(b2)}finally{close(a);close(b);await app.close()}})
