import { createServer } from 'node:http'
import { existsSync, readFileSync } from 'node:fs'
import { extname, resolve } from 'node:path'
import { CanvasStore, CanvasCoreError } from '../../../packages/canvas-core/src/index.js'
import { SqliteEventLedger } from '../../../packages/event-ledger/src/index.js'
import type { CanvasTransaction } from '../../../packages/canvas-schema/src/index.js'
import { SvgCanvasAdapter } from '../../../packages/adapter-svg/src/index.js'
import type { Viewport } from '../../../packages/canvas-adapter/src/index.js'
import { StateVectorSyncRoom, type SyncUpdate } from '../../../packages/state-vector-sync/src/index.js'
import { SqliteSyncUpdateLog } from '../../../packages/sync-ledger/src/index.js'
import { CanvasWebSocketHub } from '../../../packages/websocket-sync/src/index.js'
import { CanvasSyncRegistry } from '../../../packages/sync-registry/src/index.js'
import { McpReferenceCanvasServer } from '../../../packages/mcp-reference-server/src/index.js'
import { DirectoryNvclTraceSink, LocalMcpCanvasClient, NvclRuntime, ReferenceSceneNvclAgent } from '../../../packages/nvcl-runtime/src/index.js'
import { DirectoryRecursiveTraceSink, REFERENCE_DETAIL_CHECKS, RecursiveNvclRuntime, ReferenceDetailNvclAgent } from '../../../packages/recursive-nvcl-runtime/src/index.js'
import { MultimodalCanvasLab, MultimodalLabError, type LabAction, type ObservationMode, type RasterCrop } from '../../../packages/multimodal-lab/src/index.js'
import { agent, createWorkspace, object, transactionId } from '../../cli/src/fixtures.js'

interface Phase6ServerOptions { port?: number; host?: string; databasePath?: string; syncDatabasePath?: string; labLeaseTtlMs?: number; now?: () => number }
function json(response:any,status:number,payload:unknown){response.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store'});response.end(JSON.stringify(payload,null,2))}
function readBody(request:any):Promise<unknown>{return new Promise((resolveBody,reject)=>{const chunks:Uint8Array[]=[];request.on('data',(chunk:Uint8Array)=>chunks.push(chunk));request.on('end',()=>{try{const text=Buffer.concat(chunks).toString('utf8');resolveBody(text?JSON.parse(text):{})}catch(error){reject(error)}});request.on('error',reject)})}
function contentType(pathname:string){switch(extname(pathname)){case'.html':return'text/html; charset=utf-8';case'.js':return'text/javascript; charset=utf-8';case'.css':return'text/css; charset=utf-8';case'.svg':return'image/svg+xml; charset=utf-8';case'.png':return'image/png';default:return'application/octet-stream'}}
function labMode(value:unknown):ObservationMode{return value==='structured'||value==='hybrid'?value:'pixel'}

export function createSeedTransaction(canvasId:string):CanvasTransaction{
  const now=new Date().toISOString(); const objects=[
    object('ground','rectangle',{x:80,y:500,width:950,height:140,zIndex:1},{role:'ground',cornerRadius:28}),
    object('moon','ellipse',{x:745,y:105,width:190,height:190,zIndex:2},{role:'moon'}),
    object('character-body','ellipse',{x:430,y:255,width:250,height:330,zIndex:5},{role:'character'}),
    object('character-face','ellipse',{x:480,y:300,width:150,height:125,zIndex:6},{role:'character-face'}),
    object('title','text',{x:390,y:225,width:360,height:70,zIndex:12},{role:'title',fontWeight:800},{text:'Native Visual Canvas'}),
    object('star-1','text',{x:180,y:145,width:55,height:55,zIndex:4},{role:'star'},{text:'★'}),
    object('star-2','text',{x:320,y:95,width:55,height:55,zIndex:4},{role:'star'},{text:'★'}),
    object('star-3','text',{x:995,y:205,width:55,height:55,zIndex:4},{role:'star'},{text:'★'}),
  ]; const palette:Record<string,{fill?:string;stroke?:string;fontSize?:number}>={ground:{fill:'#86efac',stroke:'#166534'},moon:{fill:'#fde68a',stroke:'#d97706'},'character-body':{fill:'#f9a8d4',stroke:'#9d174d'},'character-face':{fill:'#fce7f3',stroke:'#be185d'},title:{fill:'#312e81',stroke:'none',fontSize:38},'star-1':{fill:'#f59e0b',stroke:'none',fontSize:46},'star-2':{fill:'#f59e0b',stroke:'none',fontSize:46},'star-3':{fill:'#f59e0b',stroke:'none',fontSize:46}}; for(const item of objects)item.style={...item.style,...palette[item.id]}
  return{id:transactionId(),canvasId,actor:agent,intent:'Seed the Phase 2 synchronized canvas',expectedOutcome:'Create a title, character, moon, ground, and three stars',preconditions:[{type:'canvas_revision',targetId:canvasId,expected:0}],operations:objects.map(item=>({op:'create_object' as const,object:{...item,canvasId,createdAt:now,updatedAt:now}})),mode:'direct',createdAt:now,idempotencyKey:'phase2-seed-scene'}
}

export function createRepairTransaction(store:CanvasStore,canvasId:string):CanvasTransaction{
  const title=store.getObject('title'); return{id:transactionId(),canvasId,actor:agent,intent:'Repair title overlap using a synchronized local patch',expectedOutcome:'Move only the title above the character',preconditions:[{type:'canvas_revision',targetId:canvasId,expected:store.getCanvas(canvasId).revision},{type:'object_revision',targetId:title.id,expected:title.revision}],operations:[{op:'patch_object',objectId:title.id,expectedRevision:title.revision,patch:{transform:{y:55}}}],mode:'direct',createdAt:new Date().toISOString()}
}

export function createPhase6Server(options:Phase6ServerOptions={}){
  const {workspace,rootCanvas}=createWorkspace(); workspace.title='MRMIC NVCL Phase 12'; workspace.schemaVersion='0.13.0'; rootCanvas.title='Transient-preserving hybrid and opt-in Provider A/B laboratory'
  const ledger=new SqliteEventLedger(options.databasePath??':memory:'); const recovered=ledger.latestSnapshot(workspace.id); const store=new CanvasStore(workspace,rootCanvas,{eventSink:ledger},recovered?.state); const adapter=new SvgCanvasAdapter(store,{x:0,y:0,width:1200,height:800,zoom:1})
  const syncLedger=new SqliteSyncUpdateLog(options.syncDatabasePath??':memory:'); const registry=new CanvasSyncRegistry({workspaceId:workspace.id,store,adapter,persistence:syncLedger}); const room=registry.roomFor(rootCanvas.id); const hub=registry.hubFor(rootCanvas.id); const roomId=room.roomId
  const lab=new MultimodalCanvasLab({store,adapter,canvasId:rootCanvas.id,applyTransaction:async tx=>(await registry.roomFor(tx.canvasId).apply(registry.roomFor(tx.canvasId).nextUpdate('phase12-lab',tx))).result,replaceState:input=>registry.replaceAll('phase12-history',input),leaseTtlMs:options.labLeaseTtlMs,now:options.now})
  const mcp=new McpReferenceCanvasServer({store,adapter,room,roomForCanvas:id=>registry.roomFor(id),syncHandleForCanvas:id=>registry.syncHandle(id),replaceState:(clientId,input)=>registry.replaceAll(clientId,input),ledger,workspaceId:workspace.id,rootCanvasId:rootCanvas.id,lab})
  let checkpointCounter=0; adapter.subscribe(delta=>{checkpointCounter+=1; ledger.saveSnapshot({snapshotId:`checkpoint-${Date.now()}-${checkpointCounter}`,workspaceId:workspace.id,canvasId:delta.canvasId,revision:delta.revision,state:store.snapshot()})})
  const nvclRuns=new Map<string,unknown>()
  const recursiveRuns=new Map<string,unknown>()
  const sseClients=new Set<any>(); adapter.subscribe(delta=>{const message=`event: canvas_delta\ndata: ${JSON.stringify(delta)}\n\n`;for(const client of sseClients)client.write(message)})
  const publicRoot=resolve(process.cwd(),'apps/web/public')
  const server=createServer(async(request:any,response:any)=>{try{if(await mcp.handleHttp(request,response))return;const url=new URL(request.url??'/',`http://${request.headers.host??'localhost'}`);const pathname=url.pathname
    if(request.method==='GET'&&pathname==='/api/state'){const canvasId=url.searchParams.get('canvasId')??rootCanvas.id;json(response,200,{workspace:store.workspace,canvas:store.getCanvas(canvasId),viewport:await adapter.getViewport(),objects:await adapter.listObjects(canvasId),eventCount:ledger.count(),sync:{roomId:registry.roomFor(canvasId).roomId,stateVector:registry.roomFor(canvasId).stateVector(),updates:registry.roomFor(canvasId).updateCount(),presence:registry.roomFor(canvasId).presenceSnapshot(),peers:registry.hubFor(canvasId).peerCount(),handle:registry.syncHandle(canvasId)},renderUri:`/api/render.svg?canvasId=${encodeURIComponent(canvasId)}`,lab:{history:lab.historyStatus,trajectoryLength:lab.trajectory.length}});return}
    if(request.method==='GET'&&pathname==='/api/lab/observe'){json(response,200,{observation:await lab.observe(labMode(url.searchParams.get('mode'))),history:lab.historyStatus});return}
    if(request.method==='GET'&&pathname.startsWith('/api/lab/frame/')&&pathname.endsWith('.svg')){const frameId=decodeURIComponent(pathname.slice('/api/lab/frame/'.length,-4));const frame=lab.frame(frameId);if(!frame){json(response,404,{error:'Frame not found',code:'FRAME_NOT_FOUND'});return}response.writeHead(200,{'content-type':'image/svg+xml; charset=utf-8','cache-control':'private, max-age=31536000, immutable','x-mrmic-frame-id':frameId,'x-mrmic-render-sha256':frame.observation.renderSha256});response.end(frame.svg);return}
    if(request.method==='GET'&&pathname.startsWith('/api/lab/frame/')&&pathname.endsWith('.png')){const frameId=decodeURIComponent(pathname.slice('/api/lab/frame/'.length,-4));const keys=['x','y','width','height'] as const;const supplied=keys.filter(key=>url.searchParams.has(key));if(supplied.length>0&&supplied.length!==keys.length)throw new MultimodalLabError('INVALID_ACTION','PNG crop requires x, y, width and height');const crop=supplied.length===keys.length?Object.fromEntries(keys.map(key=>[key,Number(url.searchParams.get(key))])) as unknown as RasterCrop:undefined;const raster=await lab.rasterize(frameId,crop);response.writeHead(200,{'content-type':'image/png','content-length':String(raster.png.byteLength),'cache-control':'private, max-age=31536000, immutable','x-mrmic-frame-id':frameId,'x-mrmic-raster-id':raster.observation.rasterId,'x-mrmic-raster-sha256':raster.observation.sha256,'x-mrmic-source-render-sha256':raster.observation.sourceRenderSha256});response.end(raster.png);return}
    if(request.method==='GET'&&pathname.startsWith('/api/lab/raster/')&&pathname.endsWith('.png')){const rasterId=decodeURIComponent(pathname.slice('/api/lab/raster/'.length,-4));const raster=lab.raster(rasterId);if(!raster){json(response,404,{error:'Raster not found',code:'RASTER_NOT_FOUND'});return}response.writeHead(200,{'content-type':'image/png','content-length':String(raster.png.byteLength),'cache-control':'private, max-age=31536000, immutable','x-mrmic-frame-id':raster.observation.frameId,'x-mrmic-raster-id':rasterId,'x-mrmic-raster-sha256':raster.observation.sha256});response.end(raster.png);return}
    if(request.method==='GET'&&pathname==='/api/lab/trajectory'){json(response,200,{trajectory:lab.trajectory,history:lab.historyStatus});return}
    if(request.method==='GET'&&pathname==='/api/lab/benchmark/verify'){json(response,200,{verification:lab.verifyBenchmark()});return}
    if(request.method==='POST'&&pathname==='/api/lab/action'){const body=await readBody(request) as {action:LabAction;mode?:ObservationMode};json(response,200,await lab.execute(body.action,labMode(body.mode)));return}
    if(request.method==='POST'&&pathname==='/api/lab/undo'){const body=await readBody(request) as {actionId:string;frameId:string;mode?:ObservationMode};json(response,200,await lab.undo(body.actionId,body.frameId,labMode(body.mode)));return}
    if(request.method==='POST'&&pathname==='/api/lab/redo'){const body=await readBody(request) as {actionId:string;frameId:string;mode?:ObservationMode};json(response,200,await lab.redo(body.actionId,body.frameId,labMode(body.mode)));return}
    if(request.method==='POST'&&pathname==='/api/lab/benchmark/reset'){const body=await readBody(request) as {actionId:string;frameId?:string;mode?:ObservationMode};json(response,200,await lab.resetBenchmark(body.actionId,body.frameId,labMode(body.mode)));return}
    if(request.method==='GET'&&pathname==='/api/render.svg'){const canvasId=url.searchParams.get('canvasId')??rootCanvas.id;const render=await adapter.render({canvasId,includeGrid:true});response.writeHead(200,{'content-type':'image/svg+xml; charset=utf-8','cache-control':'no-store'});response.end(render.svg);return}
    if(request.method==='GET'&&pathname==='/api/events'){json(response,200,{events:ledger.list(workspace.id)});return}
    if(request.method==='GET'&&pathname==='/api/sync/status'){const canvasId=url.searchParams.get('canvasId')??rootCanvas.id;const currentRoom=registry.roomFor(canvasId),currentHub=registry.hubFor(canvasId);json(response,200,{canvasId,roomId:currentRoom.roomId,stateVector:currentRoom.stateVector(),updates:currentRoom.updateCount(),presence:currentRoom.presenceSnapshot(),peers:currentHub.peerCount(),persisted:syncLedger.count(currentRoom.roomId),handle:registry.syncHandle(canvasId)});return}
    if(request.method==='GET'&&pathname==='/api/nvcl/runs'){json(response,200,{runs:[...nvclRuns.values()],recursiveRuns:[...recursiveRuns.values()]});return}
    if(request.method==='GET'&&pathname==='/events'){response.writeHead(200,{'content-type':'text/event-stream','cache-control':'no-cache',connection:'keep-alive'});response.write(': connected\n\n');sseClients.add(response);request.on('close',()=>sseClients.delete(response));return}
    if(request.method==='POST'&&pathname==='/api/sync/update'){const update=await readBody(request) as SyncUpdate;const canvasId=url.searchParams.get('canvasId')??update.transaction.canvasId;json(response,200,await registry.roomFor(canvasId).apply(update));return}
    if(request.method==='POST'&&pathname==='/api/transaction'){const tx=await readBody(request) as CanvasTransaction;const targetRoom=registry.roomFor(tx.canvasId);const update=targetRoom.nextUpdate('http-api',tx);json(response,200,await targetRoom.apply(update));return}
    if(request.method==='POST'&&pathname==='/api/viewport'){const body=await readBody(request) as Partial<Viewport>;const current=await adapter.getViewport();await adapter.setViewport({...current,...body});json(response,200,{ok:true,viewport:await adapter.getViewport()});return}
    if(request.method==='POST'&&pathname==='/api/nvcl/reference'){const runId=`web-nvcl-${Date.now()}`;const trace=new DirectoryNvclTraceSink(resolve(process.cwd(),'artifacts','nvcl-runs'),runId);const runtime=new NvclRuntime({client:new LocalMcpCanvasClient(mcp,{actorId:'web-nvcl-agent',role:'owner'}),agent:new ReferenceSceneNvclAgent(),trace});const result=await runtime.run({runId,goal:'Create a title, character, moon, ground, and exactly three stars. Keep the title from obscuring the character and repair only the failing region.',canvasId:rootCanvas.id,maxIterations:6,checks:[{type:'count',role:'star',expected:3,rule:'three_stars'},{type:'max_overlap',foregroundId:'title',backgroundId:'character',maximum:0.10},{type:'inside_bounds',objectId:'title',bounds:{x:0,y:0,width:1200,height:800}}]});const uri=mcp.registerTrajectory(result.runId,result);const record={...result,trajectoryUri:uri};nvclRuns.set(result.runId,record);json(response,200,record);return}
    if(request.method==='POST'&&pathname==='/api/nvcl/recursive'){const runId=`web-recursive-${Date.now()}`;const recursiveTrace=new DirectoryRecursiveTraceSink(resolve(process.cwd(),'artifacts','recursive-runs'),runId);const childTrace=new DirectoryNvclTraceSink(resolve(process.cwd(),'artifacts','recursive-runs',runId,'child-runs'),`${runId}:child`);const client=new LocalMcpCanvasClient(mcp,{actorId:'web-recursive-agent',role:'owner'});const runtime=new RecursiveNvclRuntime({client,trace:recursiveTrace});const result=await runtime.run({runId,goal:'Delegate a character-detail study to a recursive child canvas, verify it, fold it, and write the result back to the parent portal.',parentCanvasId:rootCanvas.id,portal:{objectId:'character-detail-portal',childCanvasId:'canvas-character-detail',title:'Character Detail',transform:{x:820,y:560,width:320,height:160,zIndex:20},style:{fill:'#faf5ff',stroke:'#7c3aed',strokeWidth:3}},childGoal:'Create a face detail with exactly two eyes, a mouth, and a label that does not obscure the face.',childChecks:REFERENCE_DETAIL_CHECKS,childAgent:new ReferenceDetailNvclAgent(),childMaxIterations:6,childTrace});if(result.childResult)mcp.registerTrajectory(result.childResult.runId,result.childResult);const trajectoryUri=mcp.registerTrajectory(result.runId,result);const record={...result,trajectoryUri};recursiveRuns.set(result.runId,record);json(response,200,record);return}
    if(request.method==='POST'&&pathname==='/api/demo/seed'){if(store.listObjects(rootCanvas.id).length){json(response,200,{ok:true,skipped:true,reason:'Canvas already contains objects'});return}const update=room.nextUpdate('demo-agent',createSeedTransaction(rootCanvas.id));json(response,200,await room.apply(update));return}
    if(request.method==='POST'&&pathname==='/api/demo/repair'){const update=room.nextUpdate('demo-agent',createRepairTransaction(store,rootCanvas.id));json(response,200,await room.apply(update));return}
    if(request.method==='POST'&&pathname==='/api/demo/remote'){const moon=store.getObject('moon');const tx:CanvasTransaction={id:transactionId(),canvasId:rootCanvas.id,actor:{actorType:'agent',actorId:'remote-agent',instanceId:'phase2'},intent:'Remote agent changes moon color',preconditions:[{type:'canvas_revision',targetId:rootCanvas.id,expected:store.getCanvas(rootCanvas.id).revision},{type:'object_revision',targetId:moon.id,expected:moon.revision}],operations:[{op:'patch_object',objectId:moon.id,expectedRevision:moon.revision,patch:{style:{fill:'#bfdbfe',stroke:'#1d4ed8'}}}],mode:'direct',createdAt:new Date().toISOString()};json(response,200,await room.apply(room.nextUpdate('remote-agent',tx)));return}
    if(request.method==='POST'&&pathname==='/api/demo/subcanvas'){if(store.listObjects(rootCanvas.id).some(item=>item.id==='subcanvas-portal')){json(response,200,{ok:true,skipped:true});return}const now=new Date().toISOString(),childCanvasId='canvas-detail';const portal=object('subcanvas-portal','subcanvas',{x:100,y:690,width:320,height:150,zIndex:20},{role:'subcanvas-portal'},{text:'Character detail canvas',childCanvasId});portal.canvasId=rootCanvas.id;portal.style={fill:'#faf5ff',stroke:'#7c3aed',strokeWidth:3,opacity:1};const tx:CanvasTransaction={id:transactionId(),canvasId:rootCanvas.id,actor:agent,intent:'Create synchronized one-level subcanvas portal',preconditions:[{type:'canvas_revision',targetId:rootCanvas.id,expected:store.getCanvas(rootCanvas.id).revision}],operations:[{op:'create_subcanvas',object:portal,canvas:{id:childCanvasId,workspaceId:workspace.id,parentCanvasId:rootCanvas.id,parentObjectId:portal.id,title:'Character detail canvas',objectIds:[],revision:0,createdAt:now,updatedAt:now}}],mode:'direct',createdAt:now};json(response,200,await room.apply(room.nextUpdate('demo-agent',tx)));return}
    const relativePath=pathname==='/'?'index.html':pathname.replace(/^\//,'');const filePath=resolve(publicRoot,relativePath);if(!filePath.startsWith(publicRoot)||!existsSync(filePath)){json(response,404,{error:'Not found'});return}response.writeHead(200,{'content-type':contentType(filePath),'cache-control':'no-cache'});response.end(readFileSync(filePath))
  }catch(error){const status=error instanceof MultimodalLabError&&['STALE_FRAME','FRAME_NOT_FOUND','REVISION_CONFLICT'].includes(error.code)?409:error instanceof CanvasCoreError&&error.code==='REVISION_CONFLICT'?409:400;json(response,status,{error:error instanceof Error?error.message:String(error),code:error instanceof MultimodalLabError||error instanceof CanvasCoreError?error.code:'BAD_REQUEST'})}})
  server.on('upgrade',(request:any,socket:any,head:Uint8Array)=>{const url=new URL(request.url??'/',`http://${request.headers.host??'localhost'}`);if(url.pathname!=='/sync'){socket.destroy();return}const canvasId=url.searchParams.get('canvasId')??rootCanvas.id;registry.hubFor(canvasId).handleUpgrade(request,socket,head)})
  return{server,adapter,store,ledger,syncLedger,registry,room,hub,mcp,lab,nvclRuns,recursiveRuns,workspace,rootCanvas,recoveredSnapshotId:recovered?.snapshotId,createSeedTransaction:()=>createSeedTransaction(rootCanvas.id),createRepairTransaction:()=>createRepairTransaction(store,rootCanvas.id),async start(){const port=options.port??4173,host=options.host??'127.0.0.1';await new Promise<void>(r=>server.listen(port,host,r));const address=server.address();const actualPort=typeof address==='object'&&address?address.port:port;return{port:actualPort,host,url:`http://${host}:${actualPort}`}},async close(){ledger.saveSnapshot({snapshotId:`shutdown-${Date.now()}`,workspaceId:workspace.id,canvasId:rootCanvas.id,revision:store.getCanvas(rootCanvas.id).revision,state:store.snapshot()});mcp.close();for(const client of sseClients)client.end();await new Promise<void>((r,j)=>server.close((e:Error|undefined)=>e?j(e):r()));ledger.close();syncLedger.close()}}
}

export const createPhase5Server=createPhase6Server
export const createPhase4Server=createPhase6Server
export const createPhase3Server=createPhase6Server
export const createPhase2Server=createPhase6Server
export const createPhase1Server=createPhase6Server
export const createPhase7Server=createPhase6Server
export const createPhase8Server=createPhase6Server
export const createPhase9Server=createPhase6Server
export const createPhase10Server=createPhase6Server
export const createPhase11Server=createPhase6Server
export const createPhase12Server=createPhase6Server
if(process.argv[1]?.endsWith('server.js')){const app=createPhase12Server({port:Number(process.env.PORT??4173),host:process.env.HOST??'127.0.0.1',databasePath:process.env.MRMIC_DB??':memory:',syncDatabasePath:process.env.MRMIC_SYNC_DB??':memory:'});app.start().then(({url})=>console.log(`MRMIC/NVCL Phase 12 hybrid observation lab running at ${url}`)).catch(error=>{console.error(error);process.exitCode=1})}
